### ISSUE TITLE
Allow custom matcher definition

### ISSUE THREAD

**Issue by terrainoob** [levaleureux/dr_spec#3]
Allow users to add custom matchers/matcher libraries (like [https://arjanvandergaag.nl/blog/rspec-matchers.html](https://arjanvandergaag.nl/blog/rspec-matchers.html))

This will allow us to add things like:

- specific DR/game dev matchers
- array matchers
- xml matchers
- [json matchers](https://github.com/PikachuEXE/rspec-json_matchers)
etc.

**Comment by levaleureux** [comment]
@terrainoob this PR do 2 things https://github.com/levaleureux/dr_spec/pull/9/files
So I will extract matcher from it and create a PR for develop branch.
